name: Test Hello World

on:
  workflow_dispatch:
    inputs:
      name:
        description: '名前を入力してください'
        required: true
        default: 'World'

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello World From Env
        run: echo "${{secrets.MY_SECRET}}"