name: Hello World

on:
  push:
    branches: [ "main" ]

jobs:
  hello:
    runs-on: ubuntu-latest
    env: "Hello Universal!"

    steps:
      - name: Print Hello World From Env
        uses: echo "${{env.GREETING}}"