# .github/workflows/test_hello_world.yml
name: TEST Hello World

on:
  workflow_dispatch:

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello from manual GitHub Action!"
